### ISSUE TITLE
Seams in the Apollo heightmap

### ISSUE THREAD

**Issue by Khodyn** [cgcostume/pubg-maps#11]
There appear to be seams on the Apollo heightmap between each grid space, where the geometry is flatter.

![image](https://user-images.githubusercontent.com/49518050/67614147-30461380-f803-11e9-9ba6-ae8dfa5ba5c4.png)

![image](https://user-images.githubusercontent.com/49518050/67614148-363bf480-f803-11e9-9578-5a4f07200916.png)

![image](https://user-images.githubusercontent.com/49518050/67614154-61264880-f803-11e9-96ec-f47057ca811d.png)

This might be because the different terrain chunks aren't being joined together properly.

**Comment by Khodyn** [comment]
Hello?

**Comment by cgcostume** [comment]
Hi, thanks for the report. I'll try to reproduce and get into this within the next days.

**Comment by cgcostume** [comment]
hey, it seems that the seams are already within the original data. So the edges are redundant:

![fortnite-apollo-tiles-moep](https://user-images.githubusercontent.com/3909980/69801393-6d713d00-11d7-11ea-94cc-814913418dcb.png)

I adjusted the script for apollo to stich accordingly and updated the final maps, so this should be fixed ...

![fortnite-apollo-tiles-previs](https://user-images.githubusercontent.com/3909980/69803766-4cabe600-11dd-11ea-9b06-f4c20cf90765.png)

**Comment by Khodyn** [comment]
Thank you :D

**Comment by Khodyn** [comment]
Oh, looks like there's still a seam left near the center of the map and the spawn island is still full of seams...
![image](https://user-images.githubusercontent.com/49518050/69845221-f4034880-12c3-11ea-9335-aa9e05e219e3.png)
![image](https://user-images.githubusercontent.com/49518050/69845254-1c8b4280-12c4-11ea-8e9f-01bb8c19b376.png)
![image](https://user-images.githubusercontent.com/49518050/69845305-5e1bed80-12c4-11ea-86ed-1301e8c3225f.png)
