### ISSUE TITLE
Regular Color PNGs

### ISSUE THREAD

**Issue by PowerBroker2** [cgcostume/pubg-maps#15]
I was wondering: do you have regular color PNGs of the same exact dimensions and resolution of each of the height maps? I'd like to correlate the color pngs to the height values in the height maps if possible

**Comment by cgcostume** [comment]
sorry, no - i've tried this, but this is a much harder problem and afaik it does not exist within the data directly/pre-computed. It requires reading all textures and terrain meta data (roads, etc., all encoded in the data) and render the terrain as it is done within the game ...

**Comment by PowerBroker2** [comment]
I don't need a computed png - a normal map (even including town names and grid lines) would be perfectly fine as long as the resolution is the same. Don't worry about it, just wondering if you already had something
