### ISSUE TITLE
No such File or directory 

### ISSUE THREAD

**Issue by YoshiCrystal** [cgcostume/pubg-maps#17]
Hello, I was trying to export the Athena Landscape from an older version of Fortnite and it gives me this error:

`C:\Users\User\Desktop\map>C:\Users\User\Desktop\map\fortnite-tga-slice_athena.py -p .\UmodelExport\ -m athena
extracting 144 tiles (normal and height data) ...
Traceback (most recent call last):
  File "C:\Users\User\Desktop\map\fortnite-tga-slice_athena.py", line 194, in <module>
    extract_tiles(asset_path, offset_lookup[key], height_composite, normal_composite)
  File "C:\Users\User\Desktop\map\fortnite-tga-slice_athena.py", line 78, in extract_tiles
    tile = Image.open(tile_path)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\Desktop\\map\\UmodelExport\\Game\\Athena\\Maps\\Landscape\\Athena_Terrain_LS_00\\Texture2D_123.tga'` 

I went to Athena_Terrain_LS_00 and there was no Texture2D_123.tga.
Does anyone know what to do in this situation?

**Comment by nevecex** [comment]
The latest script is made for Athena 9.30 ( Fortnite v9.30 ), if you want an older version you can look here in commits https://github.com/cgcostume/pubg-maps/commits/master ( 7.00, 7.20, 8.00, 8.30, 9.00, 9.20 ). If you perhaps want a version that isn't available here send me a zip of the landscape folder and the version you are trying to export.

**Comment by YoshiCrystal** [comment]
I'll send you a zip with the landscape, it's from Fortnite 1.8
[UmodelExport.zip](https://github.com/cgcostume/pubg-maps/files/4377119/UmodelExport.zip)

**Comment by nevecex** [comment]
Here you go, sorry for the late answer.

[Height map Fortnite v1.80](https://user-images.githubusercontent.com/10382614/77788531-b63fe200-7061-11ea-9d4b-919c17a984ea.png)
[Normal map Fortnite v1.80](https://user-images.githubusercontent.com/10382614/77788542-bc35c300-7061-11ea-9a2e-1c4eb5f19565.png)

[Script](https://pastebin.com/raw/hdbBzVHs)

**Comment by YoshiCrystal** [comment]
Thanks for the help!
