### ISSUE TITLE
fortnite chapter 2 map?

### ISSUE THREAD

**Issue by Blenux** [cgcostume/pubg-maps#19]
Any chance on a update to the current Fortnite Chapter 2 map, still can't get the script to run for the life of me.

**Comment by nevecex** [comment]
Can you upload the zip of the landscape folder here?

**Comment by Blenux** [comment]
Sorry was busy totally forgot to reply, here it is.


[Landscape.zip](https://github.com/cgcostume/pubg-maps/files/5194910/Landscape.zip)
