### ISSUE TITLE
Fortnite chapter 1 season 2 map ?

### ISSUE THREAD

**Issue by Elyabel** [cgcostume/pubg-maps#20]
Hello can you make the chapter 1 season 2 map please ?

**Comment by nevecex** [comment]
Yes, can you upload the landscape folder here please? Thanks

**Comment by Elyabel** [comment]
Hey I don't have the landscape but its possible to make this on a picture ? 
https://i.imgur.com/ex0dZDA.jpg

**Comment by nevecex** [comment]
No, you need to find someone that has the old version of fortnite still downloaded and get them to send you the folder. I don't have it and I don't know anyone that has it. This is the oldest version this project has, maybe it can be of use to you. [Landscape](https://github.com/cgcostume/pubg-maps/tree/acce59c8ea005a3315e133748267963470ad28d6/athena)

**Comment by Elyabel** [comment]
ohh I have a friend with the old files ! wait I ask him if he can send me the files :D

**Comment by nevecex** [comment]
Think this might be from around that season? [Fortnite 1.8](https://github.com/cgcostume/pubg-maps/issues/17#issuecomment-605204134)

**Comment by Elyabel** [comment]
omg yea !

**Comment by nevecex** [comment]
Awesome, if that's all you need please close the issue

**Comment by Elyabel** [comment]
ok thanks for helping me
