### ISSUE TITLE
Fortnite heightmap higher resolution?

### ISSUE THREAD

**Issue by jhall39** [cgcostume/pubg-maps#23]
Is it possible to make one heightmap image higher resolution than 1536x1536 or is that the best resolution available in the files?

**Comment by nevecex** [comment]
That is the best resolution unfortunately. This is what the engine is
working with, it also applies surface smoothing to the heightmap. You could
try using a similar thing in the 3d tool of your choice if your terrain is
pixelated. Alternatively you could try those AI image upscalers.

**Comment by cgcostume** [comment]
The normal map in combination with the height map could theoretically provide a little bit more detail.
This would be true if and only if (1) the normals are used smoothly/interpolated over the individual terrain patches and/or (2) the normals are not just encoding the terrain normals (which could be derived directly from the height map) but have been touched/enhanced/modified by terrain editing tools or designers instead.

**Comment by jhall39** [comment]
Thank you both for answering my question. I'll keep working with it. Thank you for this tool btw, it is very cool.
