### ISSUE TITLE
Fortnite Map

### ISSUE THREAD

**Issue by Blenux** [cgcostume/pubg-maps#3]
Hey man, is there any sort of way to do this for Fortnites map?, maps can be found in the pak files with umodel at, 

Athena/Maps/Landscape/Athena_Terrain_LS_00.umap
Athena/Maps/Landscape/Athena_Terrain_LS_01.umap
Athena/Maps/Landscape/Athena_Terrain_LS_02.umap
Athena/Maps/Landscape/Athena_Terrain_LS_03.umap
Athena/Maps/Landscape/Athena_Terrain_LS_04.umap
Athena/Maps/Landscape/Athena_Terrain_LS_05.umap

each Texture2D makes comes out has 128x128px (and there is alot in one umap alone) , so not sure if it is has easily has you did PUBG Maps.

Thanks..

**Comment by cgcostume** [comment]
added a fortnite script and extracted the athena map - currently there are missing pieces within the water area ... but the landscape is complete

**Comment by cgcostume** [comment]
since there are borders within the normal map I presume the gaps are intentional to reduce GPU memory footprint

**Comment by Blenux** [comment]
Hi again, I'm trying to do the fortnite map, but everytime I run the script code for it, nothing happens and the fortnite-tga-slice.py opens up in sublime text, I have the script and extracted texture2D's in C:\Slice with the \UmodelExport\Athena\Maps\Landscape\Athena_Terrain_LS_ Folders with each of there Texture2D files inside them in it, is that the right way to do it, or user error?

**Comment by shadowlpd** [comment]
How did you know where the Parts of the Image must be set? Or can you program a Code so that the little Alpha Map pictures are converted to one Alpha Map picture, because in the folders are the Alpha Map Pictures too?

Thanks
