### ISSUE TITLE
SRTM Data

### ISSUE THREAD

**Issue by nerdbeere** [cgcostume/pubg-maps#5]
Hey,

awesome that you found and extracted the fortnite height map.

Do you think there's a way to to convert that into SRTM data?
I'd like to import it into my osm database for a project of mine.

Julian

**Comment by cgcostume** [comment]
Thanks for you feedback. Converting the heights to the digital elevation of an `.hgt` file for SRTM should be straight forward. https://dds.cr.usgs.gov/srtm/version2_1/Documentation/SRTM_Topo.pdf states:

> The DEM is provided as 16-bit signed integer data in a simple binary raster. There are no header
or trailer bytes embedded in the file. The data are stored in row major order (all the data for row
1, followed by all the data for row 2, etc.).

> All elevations are in meters referenced to the WGS84/EGM96 geoid as documented at http://
www.NGA.mil/GandG/wgsegm/.

> Byte order is Motorola ("big-endian") standard with the most significant byte first. Since they are
signed integers elevations can range from -32767 to 32767 meters, encompassing the range of
elevation to be found on the Earth.

> These data also contain occassional voids from a number of causes such as shadowing, phase
unwrapping anomalies, or other radar-specific causes. Voids are flagged with the value -32768.

Here is a python code snippet that might do the job (the endianness might need to be swapped):

```python
import argparse, numpy, os
from PIL import Image

parser = argparse.ArgumentParser()
parser.add_argument('source', help = 'source image (16bit-luminance input)')

args = parser.parse_args()

source_path = args.source
assert os.path.isfile(source_path)
target_path = os.path.splitext(os.path.basename(source_path))[0] + '.hgt'
# assert not os.path.isfile(target_path)

source = Image.open(source_path)
assert source.mode == 'I' or source.mode == 'L'

elevation_uint16 = numpy.asarray(source, dtype = numpy.uint16, order = 'C')
elevation_uint16.tofile(target_path)
```

Running, e.g., `py .\srtm.py fortnite_athena_height_l16_lod0.png` produces a `fortnite_athena_height_l16_lod0.hgt` file with binary signed 16-bit elevation.
